[book]
authors = ["BitNet Contributors <bitnet@EffortlessMetrics.com>"]
language = "en"
multilingual = false
src = "."
title = "BitNet Documentation"

[build]
build-dir = "book"
create-missing = false
