name: Shell Lint
on:
  pull_request:
    paths: ["scripts/*.sh"]
  push:
    branches: [main]
    paths: ["scripts/*.sh"]

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ludeeus/action-shellcheck@v2
        with:
          scandir: "scripts"
