name: Shell Lint
on:
  pull_request:
    paths: ["scripts/*.sh"]
  push:
    branches: [main]
    paths: ["scripts/*.sh"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955  # v4
      - uses: ludeeus/action-shellcheck@00cae500b08a931fb5698e11e79bfbd38e612a38  # v2.0.0
        with:
          scandir: "scripts"
          severity: error  # Only fail on errors, not warnings
