name: Shell Lint
on:
  pull_request:
    paths: ["scripts/*.sh"]
  push:
    branches: [main]
    paths: ["scripts/*.sh"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955  # v4
      - uses: ludeeus/action-shellcheck@d7db0bad1bb8baf8b49db42e663f00a93f7d8ba6  # v2
        with:
          scandir: "scripts"
